### PR TITLE
Histogram fillnd

### PR DESCRIPTION
**Pull request by jrmlhermitte**
note sure if this is the proper way, but I needed to make this change to get the 3D hist to work on my simulation. If anything else comes up should I post here or send as a comment to the other branch?

### CODE REVIEW

**Comment by pavoljuhas** [comment]
Small point - can you change this PR to be w/r to the add-histogram branch?
If not, no problem, I will merge to the add-histogram anyway.

**Comment by jrmlhermitte** [comment]
yes oops, i meant to put -1. ><
and yes, wrong branch... sorry. I'll have to create a new PR. Apparently, github doesn't offer a featureto change branches after PR is submitted.
I'm also assuming you mean histogram-fillnd?

**Comment by pavoljuhas** [comment]
No need for a new PR, I can merge this to histogram-fillnd.

**Comment by jrmlhermitte** [comment]
ok, sorry for all the commits (I can squash them if you prefer), small typos I did not check. It runs, but we might need to discuss the Nd histogram. I cannot get it to work assuming a 2D detector (so using a 3d histogram, 1 dimension bins counts, the other two are a 2D detector). I will try to more carefully review my simulation code to be sure it's not something silly I have done on my end.

(and thanks for the merge directly to hist branch)

**Comment by jrmlhermitte** [comment]
finally i will close it. there is another line modification that requires discussion. this PR does not elucidate the lines in question. thanks for the offer

**Pull request closed without merging**
